Development
web-eid/ocsp-php pull request #1
Opened 2022-08-15 11:24 UTC by groonguido

2022-08-22 07:43 UTC, metsma approved these changes

2022-12-02 20:47 UTC, mrts requested changes

2022-12-02 20:47 UTC, mrts commented on src/OcspResponse.php
> +                "Could not decode OcspResponse->responseBytes->responseType"
There's a mistake in the error message:
```suggestion
                "Could not decode OcspResponse->responseBytes->response"
```

2022-12-02 20:47 UTC, mrts commented on src/OcspResponse.php
> +                "OCSP response must contain the responder certificate, but non was provided"
```suggestion
                "OCSP response must contain the responder certificate, but none was provided"
```

2022-12-05 15:15 UTC, merged