Add GitHub action to run tests
web-eid/ocsp-php pull request #12
Opened 2024-03-08 11:30 UTC by mrts

Signed-off-by: Mart Somermaa <mrts@users.noreply.github.com>

2024-03-08 12:35 UTC, metsma requested changes

2024-03-08 12:35 UTC, metsma commented on .github/workflows/php.yml
> +    - uses: actions/checkout@v3
Deprecated

2024-03-08 12:35 UTC, metsma commented on .github/workflows/php.yml
> +      uses: actions/cache@v3
Deprecated

2024-03-08 14:04 UTC, mrts commented on .github/workflows/php.yml
> +      uses: actions/cache@v3
Thanks again, fixed

2024-03-12 10:53 UTC, kristelmerilain approved these changes

2024-03-12 10:55 UTC, merged